[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  SECRETS_SCAN_OMIT_KEYS = "NODE_ENV,CLAUDE_MODEL,CLAUDE_QUICK_MODEL,CLAUDE_MAX_TOKENS,CLAUDE_STANDARD_MODEL,CLAUDE_COMPREHENSIVE_MODEL,CLAUDE_REQUESTS_PER_MINUTE,SERPER_REQUESTS_PER_MINUTE,FIRECRAWL_REQUESTS_PER_MINUTE"